global:
  scrape_interval: 15s  # How often to scrape targets by default
  evaluation_interval: 15s  # How often to evaluate rules
  scrape_timeout: 10s  # Timeout for scraping targets

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Kubernetes Nodes, Pods, and Services
  - job_name: 'kubernetes'
    kubernetes_sd_configs:
      - role: node
      - role: pod
      - role: service
    relabel_configs:
      # Keep only 'service' role
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: 'grafana'

  # Scrape Grafana instance on the control node
  - job_name: 'grafana'
    static_configs:
      - targets: ['172.20.0.1:3000']  # Replace with Grafana control node's IP and port
