apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ./docker/prome/docker-compose.yml convert -o k8s
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: prometheus
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ./docker/prome/docker-compose.yml convert -o k8s
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: prometheus
    spec:
      containers:
        - image: prometheus
          name: prometheus
          ports:
            - containerPort: 9090
              protocol: TCP
      restartPolicy: Always
