apiVersion: v1
kind: Service
metadata:
  
  annotations:
    kompose.cmd: kompose --file ./docker/prome/docker-compose.yml convert -o k8s
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: prometheus
  name: prometheus-service
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      nodePort: 30000
  selector:
    app: prometheus