- name: Distribute Control Node's Public SSH Key
  hosts: all
  become: true
  tasks:
    - name: Ensure DevOps user exists
      user:
        name: DevOps
        state: present
        shell: /bin/bash

    - name: Ensure .ssh directory exists for DevOps user
      file:
        path: /home/DevOps/.ssh
        state: directory
        owner: DevOps
        group: DevOps
        mode: '0700'

    - name: Add control node's public key to DevOps authorized_keys
      authorized_key:
        user: DevOps
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/control_node_id_rsa.pub') }}"
